# Generated by Django 3.2a1 on 2021-02-23 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education_kids', '0002_course_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='mark_course',
        ),
    ]
