# Generated by Django 3.2a1 on 2021-03-01 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education_kids', '0003_remove_course_mark_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='photo',
            new_name='image',
        ),
    ]
