# Generated by Django 3.2a1 on 2021-03-01 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education_kids', '0004_rename_photo_course_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='image',
            new_name='photo_1',
        ),
    ]
