# Generated by Django 3.2a1 on 2021-03-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_kids', '0006_auto_20210302_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='photo',
            new_name='photo_3',
        ),
        migrations.RenameField(
            model_name='pupil',
            old_name='photo',
            new_name='photo_1',
        ),
        migrations.AddField(
            model_name='teacher',
            name='photo_1',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
