# Generated by Django 3.2a1 on 2021-03-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_kids', '0007_auto_20210302_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default='', verbose_name='Описание курса'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='description',
            field=models.TextField(default='', verbose_name='Информация о преподавателе'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='name_course',
            field=models.CharField(max_length=100, verbose_name='Название курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='photo_1',
            field=models.ImageField(upload_to='', verbose_name='Рисунок(1)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='photo_2',
            field=models.ImageField(upload_to='', verbose_name='Рисунок(2)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='photo_3',
            field=models.ImageField(upload_to='', verbose_name='Рисунок(3)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price_course',
            field=models.IntegerField(default=0, verbose_name='Стоимость курса'),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя ученика'),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='photo_1',
            field=models.ImageField(upload_to='', verbose_name='Рисунок(1)'),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='profile',
            field=models.CharField(max_length=100, verbose_name='Работы ученика'),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='surname',
            field=models.CharField(max_length=100, verbose_name='Фамилия ученика'),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='surname_teacher',
            field=models.CharField(max_length=100, verbose_name='Фамилия преподавателя'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='education_level',
            field=models.CharField(max_length=100, verbose_name='Преподаваемые дисциплины'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя преподавателя'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo_1',
            field=models.ImageField(upload_to='', verbose_name='Рисунок(1)'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='surname',
            field=models.CharField(max_length=100, verbose_name='Фамилия преподавателя'),
        ),
    ]
