# Generated by Django 3.2a1 on 2021-03-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_kids', '0008_auto_20210307_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Информация о достижениях')),
                ('photo_1', models.ImageField(upload_to='', verbose_name='Рисунок(1)')),
                ('photo_2', models.ImageField(upload_to='', verbose_name='Рисунок(2)')),
                ('photo_3', models.ImageField(upload_to='', verbose_name='Рисунок(3)')),
                ('photo_4', models.ImageField(upload_to='', verbose_name='Рисунок(4)')),
            ],
        ),
    ]
