# Generated by Django 3.2a1 on 2021-03-07 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education_kids', '0009_achievements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievements',
            name='photo_4',
        ),
    ]
