# Generated by Django 3.2a1 on 2021-03-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_kids', '0010_remove_achievements_photo_4'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='video',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
