# Generated by Django 3.2a1 on 2021-03-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_kids', '0012_alter_course_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='video',
            field=models.FileField(upload_to=''),
        ),
    ]
