# Generated by Django 3.2a1 on 2021-03-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_kids', '0013_alter_course_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_main', models.CharField(max_length=100, verbose_name='Название курса')),
                ('description_main', models.TextField(verbose_name='Описание курса')),
                ('video_main', models.FileField(upload_to='', verbose_name='Видео')),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='video',
            field=models.FileField(upload_to='', verbose_name='Видео'),
        ),
    ]
