# Generated by Django 3.2a1 on 2021-03-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_kids', '0014_auto_20210318_1953'),
    ]

    operations = [

        migrations.AlterField(
            model_name='main',
            name='name_main',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
