# Generated by Django 3.2a1 on 2021-03-31 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_kids', '0015_auto_20210323_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievements',
            name='photo_4',
            field=models.ImageField(default='', upload_to='', verbose_name='Рисунок(4)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='achievements',
            name='photo_5',
            field=models.ImageField(default='', upload_to='', verbose_name='Рисунок(5)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='achievements',
            name='photo_6',
            field=models.ImageField(default='', upload_to='', verbose_name='Рисунок(6)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='main',
            name='photo_1',
            field=models.ImageField(default='', upload_to='', verbose_name='Рисунок(1)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='main',
            name='photo_2',
            field=models.ImageField(default='', upload_to='', verbose_name='Рисунок(2)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='main',
            name='photo_3',
            field=models.ImageField(default='', upload_to='', verbose_name='Рисунок(3)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='main',
            name='photo_4',
            field=models.ImageField(default='', upload_to='', verbose_name='Рисунок(4)'),
            preserve_default=False,
        ),
    ]
